depend: [Vault, ProtocolLib, PlaceholderAPI, MythicMobs]

name: Guilde
main: fr.stellios.guilde.Main
authors: [LeGarri, StreeTixX]
version: 1.0
api-version: 1.16

commands:
  guilde:
    description: permet d'utiliser la commande /guilde
    aliases: [gl]
    
permissions:
 guilde.use:
    description: use guilde command
    default: op